dbt_transformation:
  outputs:
    dev:
      dataset: "{{ env_var('DBT_GOOGLE_BIGQUERY_DATASET') }}"
      # dataset: marketing_analytics_dwh
      timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('DBT_GOOGLE_BIGQUERY_KEYFILE') }}"
      # keyfile: ../.gcloud/dbt-service-account.json
      location: EU
      method: service-account
      priority: interactive
      project: "{{ env_var('DBT_GOOGLE_PROJECT') }}"
      # project: loyal-saga-416712
      threads: 32
      type: bigquery
  target: dev