# dbt_transformation:
#   outputs:
#     dev:
#       dataset: "{{ env_var('DBT_GOOGLE_BIGQUERY_DATASET') }}"
#       job_execution_timeout_seconds: 300
#       job_retries: 1
#       keyfile: "{{ env_var('DBT_GOOGLE_BIGQUERY_KEYFILE') }}"
#       location: EU
#       method: service-account
#       priority: interactive
#       project: "{{ env_var('DBT_GOOGLE_PROJECT') }}"
#       threads: 32
#       type: bigquery
#   target: dev
dbt_transformation:
  outputs:
    dev:
      dataset: marketing_analytics_dwh
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/advendio/.dbt/dbt-bq-marketing.json
      location: EU
      method: service-account
      priority: interactive
      project: loyal-saga-416712
      threads: 1
      type: bigquery
  target: dev