name: dbt_orchestration

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
env:
  DBT_PROFILES_DIR: ./
  DBT_GOOGLE_PROJECT: ${{ secrets.DBT_GOOGLE_PROJECT }}
  DBT_GOOGLE_BIGQUERY_DATASET: ${{ secrets.DBT_GOOGLE_BIGQUERY_DATASET }}
  DBT_GOOGLE_BIGQUERY_KEYFILE: ./.gcloud/dbt-service-account.json

jobs: 
  dbt_orchestration: 
    name: dbt_orchestration
    runs-on: ubuntu-latest
  
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: "3.11.8"

      - name: Authenticate using service account
        run: |
          mkdir -p ./.gcloud/
          echo '$KEYFILE' > ./.gcloud/dbt-service-account.json
        shell: bash
        env:
          KEYFILE: ${{secrets.DBT_GOOGLE_BIGQUERY_KEYFILE}}

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Print current directory
        run: pwd

      - name: Install dbt dependencies
        run: |
          cd dbt_transformation
          dbt deps 

      - name: Print current directory
        run: pwd

      - name: Run dbt seed 
        run: |
          cd dbt_transformation
          dbt seed 
      - name: Run dbt model 
        run: |
          dbt run 
      - name: Test dbt model
        run: |
          dbt test 
      - name: Generate dbt documentation
        run: |
          dbt docs generate