name: dbt_orchestration

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
env:
  DBT_PROFILES_DIR: ./
  DBT_GOOGLE_PROJECT: ${{ vars.DBT_GOOGLE_PROJECT }}
  DBT_GOOGLE_BIGQUERY_DATASET: ${{ vars.DBT_GOOGLE_BIGQUERY_DATASET }}
  DBT_GOOGLE_BIGQUERY_KEYFILE: ../dbt_transformation/.gcloud/dbt-service-account.json

jobs: 
  dbt_orchestration: 
    name: dbt_orchestration
    runs-on: ubuntu-latest
  
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: "3.11.8"

      - name: Authenticate using service account
        run: |
          mkdir -p ./dbt_transformation/.gcloud/ 
          echo "$KEYFILE_CONTENTS" > ./dbt_transformation/.gcloud/dbt-service-account.json
        shell: bash
        env: 
            KEYFILE_CONTENTS: ${{ secrets.DBT_GOOGLE_BIGQUERY_KEYFILE }}

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Debugging Output
        run: |
          ls -al ./dbt_transformation/.gcloud/
          cat ./dbt_transformation/.gcloud/dbt-service-account.json

      - name: Run dbt debug
        working-directory: ./dbt_transformation
        run: |
          dbt debug

      - name: Install dbt dependencies
        working-directory: ./dbt_transformation
        run: |
          dbt deps 
    
      - name: Run dbt seed 
        working-directory: ./dbt_transformation
        run: |
          dbt seed --target dev

      - name: Test dbt model
        working-directory: ./dbt_transformation
        run: |
          dbt test --target dev

      - name: Run dbt model 
        working-directory: ./dbt_transformation
        run: |
          dbt run --target dev

      - name: Generate dbt documentation
        working-directory: ./dbt_transformation
        run: |
          dbt docs generate --target dev